<?php

namespace AppBundle\Repository;

/**
 * OrderedMealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderedMealRepository extends \Doctrine\ORM\EntityRepository
{
}
